---
- name: Deploy NextJS Application
  hosts: production
  become: yes
  vars_files:
    - vars/secrets.yml
  
  tasks:
    # ==========================
    # PULL CODE MỚI NHẤT
    # ==========================
    
    - name: Pull latest code from GitHub
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes
      register: git_result
    
    - name: Show git pull result
      debug:
        msg: "Git repository updated. Changed: {{ git_result.changed }}"
    
    # ==========================
    # CẬP NHẬT .ENV
    # ==========================
    
    - name: Update .env file
      copy:
        content: |
          NEXT_PUBLIC_SUPABASE_URL={{ supabase_url }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY={{ supabase_anon_key }}
          NEXT_PUBLIC_ADMIN_EMAILS={{ admin_emails }}
          DATABASE_URL={{ database_url }}
          DIRECT_URL={{ direct_url }}
        dest: "{{ app_dir }}/.env"
        mode: '0600'
    
    # ==========================
    # BUILD VÀ DEPLOY DOCKER
    # ==========================
    
    - name: Build Docker image
      command: docker compose build
      args:
        chdir: "{{ app_dir }}"
      environment:
        NEXT_PUBLIC_SUPABASE_URL: "{{ supabase_url }}"
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "{{ supabase_anon_key }}"
        NEXT_PUBLIC_ADMIN_EMAILS: "{{ admin_emails }}"
        DATABASE_URL: "{{ database_url }}"
        DIRECT_URL: "{{ direct_url }}"
    
    - name: Stop old containers
      command: docker compose down
      args:
        chdir: "{{ app_dir }}"
      ignore_errors: yes
    
    - name: Start new containers
      command: docker compose up -d
      args:
        chdir: "{{ app_dir }}"
    
    # ==========================
    # HEALTH CHECK
    # ==========================
    
    - name: Wait for application to be ready
      wait_for:
        port: "{{ app_port }}"
        delay: 5
        timeout: 60
        msg: "Application failed to start on port {{ app_port }}"
    
    - name: Display deployment success
      debug:
        msg: "🚀 Deployment completed successfully! App is running at https://{{ domain_name }}"